export const DEFAULT_WIDTH = 1024;
export const DEFAULT_HEIGHT = 768;
export const DEFAULT_BTN_WIDTH = "30";
export const DEFAULT_CAMERA_TEXT = 'Start Camera';
export const DEFAULT_CONTROLS_STATE = true;
export const DEFAULT_AUTO_START = false;
export const DEFAULT_FACE_DETECT = true;
export const DEFAULT_DEBUG_VALUE = false;
export const CAMERA_TOP_PADDING = "10px";
export const CAMERA_BOTTOM_PADDING = "10px";
export const CAMERA_LEFT_PADDING = "10px";
export const CAMERA_RIGHT_PADDING = "10px";
export const DEFAULT_AUTH_SUFFIX = '/sample';
export const DEFAULT_MIN_WIDTH = 140;
export const DEFAULT_MIN_HEIGHT = 220;
export const DEFAULT_ASPECT_RATIO = DEFAULT_MIN_HEIGHT / DEFAULT_MIN_WIDTH
export const DEFAULT_ERROR_OUTSINK = "out";
export const DEFAULT_MESSAGE_OUTSINK = "logMessages";